### ISSUE TITLE
Fix prologue (capitalization, some wrongly ranked attributes)

### ISSUE THREAD

**Issue by emilydidthis** [c-dacanay/nanogenmo#26]
Over time, Alex realized that She was a typical person with a reserved manner. Eva seemed well versed in romantic relationships and wanted something casual. Later that week, Eva asked Alex if they were free, but Alex never responded to Eva's message.

**Comment by c-dacanay** [comment]
Openness flipped, cap issue

**Comment by emilydidthis** [comment]
Fixed grammar/translated to tracery, but didn't make sense to include commitment and experience prose when the prologue comes after they start dating. If we want to communicate commit and exp, perhaps this would go well in a firstdate_reflection. Also want to communicate what hobbies the two like earlier so that hobby events narrated later have more context.

**Comment by emilydidthis** [comment]
If we want to communicate commit and exp, perhaps this would go well in a firstdate_reflection. Also want to communicate what hobbies the two like earlier so that hobby events narrated later have more context.
