### ISSUE TITLE
First date prologue and hobby prologues

### ISSUE THREAD

**Issue by emilydidthis** [c-dacanay/nanogenmo#33]
Fixed grammar/translated to tracery, but didn't make sense to include commitment and experience prose when the prologue comes after they start dating. If we want to communicate commit and exp, perhaps this would go well in a firstdate_reflection. Also want to communicate what hobbies the two like earlier so that hobby events narrated later have more context.

_Originally posted by @emilydidthis in https://github.com/c-dacanay/nanogenmo/issues/26#issuecomment-751497141_

**Comment by squidgetx** [comment]
nice

**Comment by c-dacanay** [comment]
emilydidthis

**Comment by squidgetx** [comment]
actually this isn't finished and it's blocking

need to supply strings for experiences that are not libido experiences

```The couple savored a quiet morning reading together. ((extra)), Philip shared his interest in performing arts```
