### ISSUE TITLE
system output styling css

### ISSUE THREAD

**Issue by emilydidthis** [c-dacanay/nanogenmo#35]
make the debugger look pretty - toggle ???

**Comment by c-dacanay** [comment]
made the toggle but .system css could use more luv?

**Comment by c-dacanay** [comment]
I'm closing this for now! We can re-open and make it shinier when Em's head isn't exploding.

**Comment by c-dacanay** [comment]
I'm closing this for now! We can re-open and make it shinier when Em's head isn't exploding.
