### ISSUE TITLE
'behind the system' page

### ISSUE THREAD

**Issue by c-dacanay** [c-dacanay/nanogenmo#36]
writing all the stuff that is interesting

**Comment by squidgetx** [comment]
decisions made on 1-12

Preface/about the project: Goals and themes <- is this the homepage, or a separate about page
- this is cancelled / should be incorporated in the homepage or introduction to other pages

"Behind the system": narratively describe system choices / code comments (low ish pri right now)

"Process": describe coworking, shift to tracery, etc. Narrative history of the project (This is mostly done already, med/hi pri to finish this)

**Comment by c-dacanay** [comment]
preface is in process, but it needs copyedit and approval from u two~
