### ISSUE TITLE
better phase change/commit narration texture

### ISSUE THREAD

**Issue by squidgetx** [c-dacanay/nanogenmo#7]
"Matthew asked to start dating. Alex agreed very enthusiastically."

**Comment by emilydidthis** [comment]
If A says I love you first, sometimes they won't say it back when B says it later.

**Comment by emilydidthis** [comment]
Don't make them only understanding if their ily is rejected

**Comment by squidgetx** [comment]
ok

**Comment by squidgetx** [comment]
We agreed to change the prose to include a statement like "But you said you loved me 17 days ago!" instead of changing the system

**Comment by squidgetx** [comment]
Emily wants to make it more frequent to have successful commit transitions though

**Comment by squidgetx** [comment]
we can tweak the numbers a bit

**Comment by squidgetx** [comment]
Next: Interest should increase with more successful dates
