### ISSUE TITLE
better fight texture

### ISSUE THREAD

**Issue by squidgetx** [c-dacanay/nanogenmo#8]
They fought because Matthew was too mature for their age.

many things can be inlcuded in fight :(

**Comment by emilydidthis** [comment]
Not showing enough love or affection.
Lack of communication.
One not paying enough attention to the other.
Not being appreciated.
Feelings.
Jealousy.
Talking to an ex-girlfriend or ex-boyfriend.
Being possessive.
Past relationships.
Whose friends we hang around more.
Housekeeping.
Chores.
Who does more work.
Not showing up when supposed to.
Sharing responsibilities.
One wants sex, the other doesn’t.
Frequency of sex.
Sexual acts.
Telling private information about relationships to others.
In-laws.
Who’s boss.
Who’s in control.
Dominance.
What to wear.
Religion.
Goals in life.
Future plans.
Children.
Who should pay for something.
One uses all of the other’s money.

**Boils down to 6**
Inadequate Attention or Affection -> neuroticism 
Jealousy and Infidelity -> neuroticism?
Chores and Responsibilities -> conscientiousness
Sex 
Control and Dominance -> agreeability
Future Plans and Money -> commitment

**Comment by emilydidthis** [comment]
It would be better to have more casual fights

**Comment by emilydidthis** [comment]
Sharon remembered a fight they had [last month] and thought about it again

**Comment by emilydidthis** [comment]
If fight aborted, bring it back up

**Comment by emilydidthis** [comment]
Instead of texting to initiate fight, you can also say, "Sharon decided to bring it up the next time they saw each other."
